# -*- coding: utf-8 -*-
"""Untitled84.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ChmyUbOV1mcTVepmIMBk2Vi9_wF1OZP
"""

import streamlit as st

st.set_page_config(
    page_title="Bea Cukai in Action",
    page_icon="🛃",
    layout="wide"
)

st.markdown(
    """
    <style>
    .main-box {
        background: linear-gradient(135deg, #0f4c75, #1b6ca8);
        padding: 45px;
        border-radius: 22px;
        color: white;
        box-shadow: 0px 6px 20px rgba(0,0,0,0.18);
    }
    .title {
        font-size: 44px;
        font-weight: 800;
        text-align: center;
        margin-bottom: 10px;
    }
    .subtitle {
        font-size: 24px;
        text-align: center;
        opacity: 0.95;
        margin-bottom: 25px;
    }
    .description {
        font-size: 17px;
        text-align: center;
        max-width: 1000px;
        margin: auto;
        line-height: 1.7;
        margin-bottom: 35px;
    }
    .section-title {
        font-size: 22px;
        font-weight: 700;
        margin-bottom: 15px;
    }
    .card {
        background: rgba(255,255,255,0.12);
        padding: 20px;
        border-radius: 16px;
        height: 100%;
    }
    ul {
        padding-left: 20px;
    }
    </style>

    <div class="main-box">
        <div class="title">🛃 Bea Cukai in Action</div>
        <div class="subtitle">Interactive Customs Dashboard</div>

        <div class="description">
            Dashboard ini menyajikan informasi komprehensif mengenai peran,
            fungsi, tugas, serta alur proses kepabeanan dan cukai yang
            dilaksanakan oleh Direktorat Jenderal Bea dan Cukai (DJBC),
            khususnya di Wilayah Aceh. Aplikasi ini dirancang sebagai media
            edukasi dan referensi bagi mahasiswa, masyarakat, serta pemangku
            kepentingan dalam memahami peran strategis Bea Cukai dalam
            menjaga kedaulatan ekonomi dan keamanan nasional.
        </div>

        <div class="section-title">🏛️ Peran Strategis DJBC</div>
        <div style="display:grid; grid-template-columns:repeat(4,1fr); gap:20px;">
            <div class="card">
                <b>💰 Revenue Collector</b>
                <ul>
                    <li>Pemungutan bea masuk</li>
                    <li>Pemungutan bea keluar</li>
                    <li>Pemungutan cukai</li>
                </ul>
            </div>
            <div class="card">
                <b>🛡️ Community Protector</b>
                <ul>
                    <li>Pencegahan penyelundupan</li>
                    <li>Pengawasan narkotika</li>
                    <li>Pengendalian barang berbahaya</li>
                </ul>
            </div>
            <div class="card">
                <b>🚢 Trade Facilitator</b>
                <ul>
                    <li>Percepatan arus barang</li>
                    <li>Pelayanan impor dan ekspor</li>
                    <li>Dukungan logistik nasional</li>
                </ul>
            </div>
            <div class="card">
                <b>🏭 Industrial Assistance</b>
                <ul>
                    <li>Fasilitas fiskal</li>
                    <li>Dukungan industri dalam negeri</li>
                    <li>Kawasan berikat dan KITE</li>
                </ul>
            </div>
        </div>

        <br>

        <div class="section-title">⚙️ Tugas dan Fungsi Utama</div>
        <div class="card">
            <ul>
                <li>Mengawasi lalu lintas barang yang masuk dan keluar daerah pabean</li>
                <li>Memungut penerimaan negara di bidang kepabeanan dan cukai</li>
                <li>Melaksanakan penegakan hukum kepabeanan dan cukai</li>
                <li>Memberikan pelayanan kepabeanan kepada pengguna jasa</li>
                <li>Mendukung kebijakan pemerintah di bidang perdagangan dan industri</li>
            </ul>
        </div>

        <br>

        <div class="section-title">🧭 Gambaran Proses Kepabeanan</div>
        <div class="card">
            <ul>
                <li><b>Impor:</b> Kedatangan barang → Pemberitahuan Impor Barang (PIB) → Pemeriksaan → Pembayaran → Pengeluaran barang</li>
                <li><b>Ekspor:</b> Pemberitahuan Ekspor Barang (PEB) → Pemeriksaan → Persetujuan → Pengapalan</li>
            </ul>
        </div>
    </div>
    """,
    unsafe_allow_html=True
)

st.markdown("<br>", unsafe_allow_html=True)